const en = {
  "home.title": "See pollution at a wetland?",
  "home.sub":
    "Take a photo. We record where you are. NEMA reviews it and you get a reward.",
  "btn.camera": "Camera",
  "btn.upload": "Upload",
  "home.tip":
    "Tip: take 2 to 3 photos and include a landmark like a building, road or tree.",
  "home.mine": "My reports",
  "home.none": "No reports yet.",
  "home.points": "Community points: {n}",
  offline: "No signal. Reports are saved and sent later.",
  "fact.1":
    "Wetlands work like sponges. They soak up heavy rain and slow floodwater.",
  "fact.2":
    "Wetlands filter water, so cleaner wetlands mean cleaner water downstream.",
  "fact.3":
    "Dumping or filling in a wetland makes floods worse in nearby neighbourhoods.",
  "queued.label": "Waiting for signal",
  "queued.badge": "Queued",
  "form.back": "← Start over",
  "form.photos": "Photos (1 to 3)",
  "form.addPhoto": "Add photo",
  "form.remove": "Remove photo {n}",
  "form.landmark": "Include a landmark, like a building, road or tree.",
  "form.category": "What is happening?",
  "form.required": "(required)",
  "form.optional": "(optional)",
  "form.severity": "How bad is it?",
  "form.describe": "Describe what you see",
  "form.galleryNote":
    "This photo is from your gallery. Check that the pin is where it was taken.",
  "form.mapHelp": "Drag the pin to where the pollution is.",
  "form.mapOffline":
    "No signal: the map cannot load, but your GPS location is saved.",
  "form.pinShift": "The pin is {m} m from your GPS reading.",
  "form.time": "Time",
  "form.locked": "recorded automatically, cannot be edited",
  "form.anon": "Report anonymously",
  "form.anonHelp":
    "NEMA reviewers won't see your name or number. You add a phone number only when you claim your reward.",
  "form.contactPhone": "Phone number so NEMA can contact you",
  "form.send": "Send to NEMA",
  "form.sending": "Sending…",
  "form.chooseCat": "Choose what is happening to send.",
  "gps.wait": "Getting your location…",
  "gps.waitSub": "Stay where you took the photo.",
  "gps.good": "Location captured",
  "gps.acc": "accurate to ±{a} m",
  "gps.weak": "Location is rough (±{a} m)",
  "gps.weakSub": "move to open sky and try again",
  "gps.denied": "Location permission was denied",
  "gps.deniedSub": "Allow location for this site, then try again.",
  "gps.fail": "Could not get your location",
  "gps.failSub": "Turn on location and try again.",
  "gps.none": "Location is not available on this device",
  "gps.retry": "Try again",
  "notice.photoRead": "Could not read that photo. Please try again.",
  "notice.screenshot":
    "Please use a photo from your camera, not a screenshot or saved image.",
  "notice.maxPhotos": "You can add up to 3 photos.",
  "notice.wait": "Please wait {m} min before sending another report.",
  "notice.saved": "Saved on your phone. It will send when you have signal.",
  "notice.phone":
    "Enter a phone number so NEMA can contact you, or report anonymously.",
  "notice.sendFail":
    "Could not send that report. Check the details and try again.",
  "status.new": "Submitted",
  "status.viewed": "Under review",
  "status.verified": "Verified",
  "status.rewarded": "Rewarded",
  "step.sent": "Photo and location sent",
  "step.received": "Received by NEMA",
  "step.thanks": "Thank you. This helps us map the problem.",
  "step.review": "Reviewed by NEMA",
  "step.reviewSub": "A person has looked at your report.",
  "step.waiting": "Waiting for NEMA to review it",
  "step.safe": "You can close this page. Your report is safe.",
  "step.next": "Next: {o}",
  "step.verified": "Verified by NEMA",
  "step.reward": "Your reward",
  "reward.title": "You earned a reward",
  "reward.body":
    "NEMA has reviewed your report. You get 1 community point and an entry in the monthly airtime draw.",
  "reward.phone": "Phone number for airtime, e.g. 0772 000 000",
  "reward.claim": "Claim reward",
  "reward.claimed":
    "Claimed. We will SMS you if you win the draw. Your number is kept apart from your report.",
  "back.home": "← Home",
  "sent.ago": "Sent {t}",
  demo: "Demo build. Do not submit real evidence yet.",
  "cat.dumping": "Dumping / waste",
  "cat.sewage": "Sewage",
  "cat.encroachment": "Encroachment / construction",
  "cat.burning": "Burning",
  "cat.drainage": "Drainage",
  "cat.other": "Other",
  "sev.low": "Low",
  "sev.medium": "Medium",
  "sev.high": "High",
  "outcome.inspector": "Inspector will visit",
  "outcome.referred": "Referred to another agency",
  "outcome.moreinfo": "Need more information",
  "form.uploadGps":
    "Location was read from the photo. Drag the pin if it is wrong.",
  "form.uploadNoGps":
    "This photo has no location. Tap the map where it was taken.",
};
export default en;
