const sw = {
  "home.title": "Umeona uchafuzi kwenye ardhioevu?",
  "home.sub":
    "Piga picha. Tunarekodi mahali ulipo. NEMA inaikagua, nawe unapata zawadi.",
  "btn.camera": "Kamera",
  "btn.upload": "Pakia",
  "home.tip":
    "Kidokezo: piga picha 2 hadi 3 na uonyeshe alama kama jengo, barabara au mti.",
  "home.mine": "Ripoti zangu",
  "home.none": "Bado hakuna ripoti.",
  "home.points": "Pointi za jamii: {n}",
  offline: "Hakuna mtandao. Ripoti zitahifadhiwa na kutumwa baadaye.",
  "fact.1":
    "Ardhioevu hufanya kazi kama sifongo: hufyonza mvua kubwa na kupunguza kasi ya mafuriko.",
  "fact.2":
    "Ardhioevu huchuja maji, kwa hiyo ardhioevu safi humaanisha maji safi chini ya mkondo.",
  "fact.3":
    "Kutupa taka au kujaza ardhioevu huongeza mafuriko kwenye mitaa ya karibu.",
  "queued.label": "Inasubiri mtandao",
  "queued.badge": "Kwenye foleni",
  "form.back": "← Anza upya",
  "form.photos": "Picha (1 hadi 3)",
  "form.addPhoto": "Ongeza picha",
  "form.remove": "Ondoa picha {n}",
  "form.landmark": "Jumuisha alama ya mahali, kama jengo, barabara au mti.",
  "form.category": "Nini kinatokea?",
  "form.required": "(lazima)",
  "form.optional": "(si lazima)",
  "form.severity": "Ni kubwa kiasi gani?",
  "form.describe": "Elezea unachokiona",
  "form.galleryNote":
    "Picha hii ni ya kwenye simu yako. Hakikisha alama iko mahali picha ilipopigwa.",
  "form.mapHelp": "Buruta alama hadi mahali penye uchafuzi.",
  "form.mapOffline":
    "Hakuna mtandao: ramani haionekani, lakini mahali pa GPS pamehifadhiwa.",
  "form.pinShift": "Alama iko mita {m} kutoka usomaji wa GPS.",
  "form.time": "Muda",
  "form.locked": "unarekodiwa wenyewe, haubadilishwi",
  "form.anon": "Ripoti bila kutaja jina",
  "form.anonHelp":
    "Wakaguzi wa NEMA hawataona jina wala namba yako. Utaweka namba ya simu tu unapodai zawadi.",
  "form.contactPhone": "Namba ya simu ili NEMA ikupigie",
  "form.send": "Tuma kwa NEMA",
  "form.sending": "Inatuma…",
  "form.chooseCat": "Chagua kinachotokea ili utume.",
  "gps.wait": "Tunapata mahali ulipo…",
  "gps.waitSub": "Kaa mahali ulipopiga picha.",
  "gps.good": "Mahali pamepatikana",
  "gps.acc": "usahihi ±{a} m",
  "gps.weak": "Mahali si sahihi sana (±{a} m)",
  "gps.weakSub": "nenda mahali wazi na ujaribu tena",
  "gps.denied": "Ruhusa ya mahali imekataliwa",
  "gps.deniedSub": "Ruhusu mahali kwa tovuti hii, kisha ujaribu tena.",
  "gps.fail": "Hatukuweza kupata mahali ulipo",
  "gps.failSub": "Washa mahali (location) na ujaribu tena.",
  "gps.none": "Mahali hapatikani kwenye kifaa hiki",
  "gps.retry": "Jaribu tena",
  "notice.photoRead": "Hatukuweza kusoma picha hiyo. Jaribu tena.",
  "notice.screenshot": "Tumia picha kutoka kwenye kamera, si picha ya skrini.",
  "notice.maxPhotos": "Unaweza kuongeza hadi picha 3.",
  "notice.wait": "Subiri dakika {m} kabla ya kutuma ripoti nyingine.",
  "notice.saved": "Imehifadhiwa kwenye simu yako. Itatumwa ukipata mtandao.",
  "notice.phone":
    "Weka namba ya simu ili NEMA ikupigie, au ripoti bila kutaja jina.",
  "notice.sendFail": "Ripoti haikutumwa. Angalia maelezo na ujaribu tena.",
  "status.new": "Imetumwa",
  "status.viewed": "Inakaguliwa",
  "status.verified": "Imethibitishwa",
  "status.rewarded": "Zawadi imetolewa",
  "step.sent": "Picha na mahali vimetumwa",
  "step.received": "Imepokelewa na NEMA",
  "step.thanks": "Asante. Hii inatusaidia kuchora tatizo.",
  "step.review": "Imekaguliwa na NEMA",
  "step.reviewSub": "Mtu ameangalia ripoti yako.",
  "step.waiting": "Inasubiri NEMA ikague",
  "step.safe": "Unaweza kufunga ukurasa huu. Ripoti yako iko salama.",
  "step.next": "Hatua inayofuata: {o}",
  "step.verified": "Imethibitishwa na NEMA",
  "step.reward": "Zawadi yako",
  "reward.title": "Umepata zawadi",
  "reward.body":
    "NEMA imekagua ripoti yako. Unapata pointi 1 ya jamii na nafasi kwenye droo ya kila mwezi ya muda wa maongezi.",
  "reward.phone": "Namba ya simu ya muda wa maongezi, mfano 0772 000 000",
  "reward.claim": "Dai zawadi",
  "reward.claimed":
    "Imedaiwa. Tutakutumia SMS ukishinda droo. Namba yako haihifadhiwi pamoja na ripoti.",
  "back.home": "← Nyumbani",
  "sent.ago": "Imetumwa {t}",
  demo: "Toleo la majaribio. Usitume ushahidi halisi bado.",
  "cat.dumping": "Utupaji taka",
  "cat.sewage": "Maji taka",
  "cat.encroachment": "Uvamizi / ujenzi",
  "cat.burning": "Uchomaji moto",
  "cat.drainage": "Mifereji",
  "cat.other": "Nyingine",
  "sev.low": "Ndogo",
  "sev.medium": "Wastani",
  "sev.high": "Kubwa",
  "outcome.inspector": "Mkaguzi atatembelea",
  "outcome.referred": "Imepelekwa kwa taasisi nyingine",
  "outcome.moreinfo": "Tunahitaji maelezo zaidi",
  "form.uploadGps":
    "Mahali pamesomwa kutoka kwenye picha. Buruta alama ikiwa si sahihi.",
  "form.uploadNoGps": "Picha hii haina mahali. Gusa ramani mahali ilipopigwa.",
};
export default sw;
